const countryData = {
  IN: { name: "India", flag: "🇮🇳", capital: "New Delhi" },
  US: { name: "United States", flag: "🇺🇸", capital: "Washington" },
  GB: { name: "United Kingdom", flag: "🇬🇧", capital: "London" },
  AU: { name: "Australia", flag: "🇦🇺", capital: "Canberra" },
  CA: { name: "Canada", flag: "🇨🇦", capital: "Ottawa" },
  JP: { name: "Japan", flag: "🇯🇵", capital: "Tokyo" },
  CN: { name: "China", flag: "🇨🇳", capital: "Beijing" },
  RU: { name: "Russia", flag: "🇷🇺", capital: "Moscow" },
  FR: { name: "France", flag: "🇫🇷", capital: "Paris" },
  DE: { name: "Germany", flag: "🇩🇪", capital: "Berlin" },
  IT: { name: "Italy", flag: "🇮🇹", capital: "Rome" },
  ES: { name: "Spain", flag: "🇪🇸", capital: "Madrid" },
  PT: { name: "Portugal", flag: "🇵🇹", capital: "Lisbon" },
  BR: { name: "Brazil", flag: "🇧🇷", capital: "Brasília" },
  MX: { name: "Mexico", flag: "🇲🇽", capital: "Mexico City" },
  AR: { name: "Argentina", flag: "🇦🇷", capital: "Buenos Aires" },
  ZA: { name: "South Africa", flag: "🇿🇦", capital: "Pretoria" },
  EG: { name: "Egypt", flag: "🇪🇬", capital: "Cairo" },
  SA: { name: "Saudi Arabia", flag: "🇸🇦", capital: "Riyadh" },
  AE: { name: "United Arab Emirates", flag: "🇦🇪", capital: "Abu Dhabi" },
  QA: { name: "Qatar", flag: "🇶🇦", capital: "Doha" },
  OM: { name: "Oman", flag: "🇴🇲", capital: "Muscat" },
  KW: { name: "Kuwait", flag: "🇰🇼", capital: "Kuwait City" },
  BD: { name: "Bangladesh", flag: "🇧🇩", capital: "Dhaka" },
  PK: { name: "Pakistan", flag: "🇵🇰", capital: "Islamabad" },
  NP: { name: "Nepal", flag: "🇳🇵", capital: "Kathmandu" },
  LK: { name: "Sri Lanka", flag: "🇱🇰", capital: "Sri Jayawardenepura Kotte" },
  BT: { name: "Bhutan", flag: "🇧🇹", capital: "Thimphu" },
  MY: { name: "Malaysia", flag: "🇲🇾", capital: "Kuala Lumpur" },
  SG: { name: "Singapore", flag: "🇸🇬", capital: "Singapore" },
  ID: { name: "Indonesia", flag: "🇮🇩", capital: "Jakarta" },
  TH: { name: "Thailand", flag: "🇹🇭", capital: "Bangkok" },
  KR: { name: "South Korea", flag: "🇰🇷", capital: "Seoul" },
  KP: { name: "North Korea", flag: "🇰🇵", capital: "Pyongyang" },
  NZ: { name: "New Zealand", flag: "🇳🇿", capital: "Wellington" },
    AF: { name: "Afghanistan", flag: "🇦🇫", capital: "Kabul" },
  AM: { name: "Armenia", flag: "🇦🇲", capital: "Yerevan" },
  AZ: { name: "Azerbaijan", flag: "🇦🇿", capital: "Baku" },
  BH: { name: "Bahrain", flag: "🇧🇭", capital: "Manama" },
  BN: { name: "Brunei", flag: "🇧🇳", capital: "Bandar Seri Begawan" },
  KH: { name: "Cambodia", flag: "🇰🇭", capital: "Phnom Penh" },
  CY: { name: "Cyprus", flag: "🇨🇾", capital: "Nicosia" },
  GE: { name: "Georgia", flag: "🇬🇪", capital: "Tbilisi" },
  IR: { name: "Iran", flag: "🇮🇷", capital: "Tehran" },
  IQ: { name: "Iraq", flag: "🇮🇶", capital: "Baghdad" },
  IL: { name: "Israel", flag: "🇮🇱", capital: "Jerusalem" },
  JO: { name: "Jordan", flag: "🇯🇴", capital: "Amman" },
  KZ: { name: "Kazakhstan", flag: "🇰🇿", capital: "Astana" },
  KG: { name: "Kyrgyzstan", flag: "🇰🇬", capital: "Bishkek" },
  LA: { name: "Laos", flag: "🇱🇦", capital: "Vientiane" },
  LB: { name: "Lebanon", flag: "🇱🇧", capital: "Beirut" },
  MV: { name: "Maldives", flag: "🇲🇻", capital: "Malé" },
  MN: { name: "Mongolia", flag: "🇲🇳", capital: "Ulaanbaatar" },
  MM: { name: "Myanmar", flag: "🇲🇲", capital: "Naypyidaw" },
  PH: { name: "Philippines", flag: "🇵🇭", capital: "Manila" },
  SY: { name: "Syria", flag: "🇸🇾", capital: "Damascus" },
  TJ: { name: "Tajikistan", flag: "🇹🇯", capital: "Dushanbe" },
  TL: { name: "Timor-Leste", flag: "🇹🇱", capital: "Dili" },
  TR: { name: "Turkey", flag: "🇹🇷", capital: "Ankara" },
  TM: { name: "Turkmenistan", flag: "🇹🇲", capital: "Ashgabat" },
  UZ: { name: "Uzbekistan", flag: "🇺🇿", capital: "Tashkent" },
  VN: { name: "Vietnam", flag: "🇻🇳", capital: "Hanoi" },
  YE: { name: "Yemen", flag: "🇾🇪", capital: "Sana'a" },
    AL: { name: "Albania", flag: "🇦🇱", capital: "Tirana" },
  AD: { name: "Andorra", flag: "🇦🇩", capital: "Andorra la Vella" },
  AT: { name: "Austria", flag: "🇦🇹", capital: "Vienna" },
  BY: { name: "Belarus", flag: "🇧🇾", capital: "Minsk" },
  BE: { name: "Belgium", flag: "🇧🇪", capital: "Brussels" },
  BA: { name: "Bosnia and Herzegovina", flag: "🇧🇦", capital: "Sarajevo" },
  BG: { name: "Bulgaria", flag: "🇧🇬", capital: "Sofia" },
  HR: { name: "Croatia", flag: "🇭🇷", capital: "Zagreb" },
  CZ: { name: "Czech Republic", flag: "🇨🇿", capital: "Prague" },
  DK: { name: "Denmark", flag: "🇩🇰", capital: "Copenhagen" },
  EE: { name: "Estonia", flag: "🇪🇪", capital: "Tallinn" },
  FI: { name: "Finland", flag: "🇫🇮", capital: "Helsinki" },
  GR: { name: "Greece", flag: "🇬🇷", capital: "Athens" },
  HU: { name: "Hungary", flag: "🇭🇺", capital: "Budapest" },
  IS: { name: "Iceland", flag: "🇮🇸", capital: "Reykjavik" },
  IE: { name: "Ireland", flag: "🇮🇪", capital: "Dublin" },
  XK: { name: "Kosovo", flag: "🇽🇰", capital: "Pristina" },
  LV: { name: "Latvia", flag: "🇱🇻", capital: "Riga" },
  LI: { name: "Liechtenstein", flag: "🇱🇮", capital: "Vaduz" },
  LT: { name: "Lithuania", flag: "🇱🇹", capital: "Vilnius" },
  LU: { name: "Luxembourg", flag: "🇱🇺", capital: "Luxembourg" },
  MT: { name: "Malta", flag: "🇲🇹", capital: "Valletta" },
  MD: { name: "Moldova", flag: "🇲🇩", capital: "Chișinău" },
  MC: { name: "Monaco", flag: "🇲🇨", capital: "Monaco" },
  ME: { name: "Montenegro", flag: "🇲🇪", capital: "Podgorica" },
  NL: { name: "Netherlands", flag: "🇳🇱", capital: "Amsterdam" },
  MK: { name: "North Macedonia", flag: "🇲🇰", capital: "Skopje" },
  NO: { name: "Norway", flag: "🇳🇴", capital: "Oslo" },
  PL: { name: "Poland", flag: "🇵🇱", capital: "Warsaw" },
  RO: { name: "Romania", flag: "🇷🇴", capital: "Bucharest" },
  SM: { name: "San Marino", flag: "🇸🇲", capital: "San Marino" },
  RS: { name: "Serbia", flag: "🇷🇸", capital: "Belgrade" },
  SK: { name: "Slovakia", flag: "🇸🇰", capital: "Bratislava" },
  SI: { name: "Slovenia", flag: "🇸🇮", capital: "Ljubljana" },
  SE: { name: "Sweden", flag: "🇸🇪", capital: "Stockholm" },
  CH: { name: "Switzerland", flag: "🇨🇭", capital: "Bern" },
  UA: { name: "Ukraine", flag: "🇺🇦", capital: "Kyiv" },
  VA: { name: "Vatican City", flag: "🇻🇦", capital: "Vatican City" },

    DZ: { name: "Algeria", flag: "🇩🇿", capital: "Algiers" },
  AO: { name: "Angola", flag: "🇦🇴", capital: "Luanda" },
  BJ: { name: "Benin", flag: "🇧🇯", capital: "Porto-Novo" },
  BW: { name: "Botswana", flag: "🇧🇼", capital: "Gaborone" },
  BF: { name: "Burkina Faso", flag: "🇧🇫", capital: "Ouagadougou" },
  BI: { name: "Burundi", flag: "🇧🇮", capital: "Gitega" },
  CM: { name: "Cameroon", flag: "🇨🇲", capital: "Yaoundé" },
  CV: { name: "Cape Verde", flag: "🇨🇻", capital: "Praia" },
  CF: { name: "Central African Republic", flag: "🇨🇫", capital: "Bangui" },
  TD: { name: "Chad", flag: "🇹🇩", capital: "N'Djamena" },
  KM: { name: "Comoros", flag: "🇰🇲", capital: "Moroni" },
  CD: { name: "Democratic Republic of the Congo", flag: "🇨🇩", capital: "Kinshasa" },
  CG: { name: "Republic of the Congo", flag: "🇨🇬", capital: "Brazzaville" },
  DJ: { name: "Djibouti", flag: "🇩🇯", capital: "Djibouti" },
  GQ: { name: "Equatorial Guinea", flag: "🇬🇶", capital: "Malabo" },
  ER: { name: "Eritrea", flag: "🇪🇷", capital: "Asmara" },
  SZ: { name: "Eswatini", flag: "🇸🇿", capital: "Mbabane" },
  ET: { name: "Ethiopia", flag: "🇪🇹", capital: "Addis Ababa" },
  GA: { name: "Gabon", flag: "🇬🇦", capital: "Libreville" },
  GM: { name: "Gambia", flag: "🇬🇲", capital: "Banjul" },
  GH: { name: "Ghana", flag: "🇬🇭", capital: "Accra" },
  GN: { name: "Guinea", flag: "🇬🇳", capital: "Conakry" },
  GW: { name: "Guinea-Bissau", flag: "🇬🇼", capital: "Bissau" },
  CI: { name: "Ivory Coast", flag: "🇨🇮", capital: "Yamoussoukro" },
  KE: { name: "Kenya", flag: "🇰🇪", capital: "Nairobi" },
  LS: { name: "Lesotho", flag: "🇱🇸", capital: "Maseru" },
  LR: { name: "Liberia", flag: "🇱🇷", capital: "Monrovia" },
  LY: { name: "Libya", flag: "🇱🇾", capital: "Tripoli" },
  MG: { name: "Madagascar", flag: "🇲🇬", capital: "Antananarivo" },
  MW: { name: "Malawi", flag: "🇲🇼", capital: "Lilongwe" },
  ML: { name: "Mali", flag: "🇲🇱", capital: "Bamako" },
  MR: { name: "Mauritania", flag: "🇲🇷", capital: "Nouakchott" },
  MU: { name: "Mauritius", flag: "🇲🇺", capital: "Port Louis" },
  MA: { name: "Morocco", flag: "🇲🇦", capital: "Rabat" },
  MZ: { name: "Mozambique", flag: "🇲🇿", capital: "Maputo" },
  NA: { name: "Namibia", flag: "🇳🇦", capital: "Windhoek" },
  NE: { name: "Niger", flag: "🇳🇪", capital: "Niamey" },
  NG: { name: "Nigeria", flag: "🇳🇬", capital: "Abuja" },
  RW: { name: "Rwanda", flag: "🇷🇼", capital: "Kigali" },
  SN: { name: "Senegal", flag: "🇸🇳", capital: "Dakar" },
  SC: { name: "Seychelles", flag: "🇸🇨", capital: "Victoria" },
  SL: { name: "Sierra Leone", flag: "🇸🇱", capital: "Freetown" },
  SO: { name: "Somalia", flag: "🇸🇴", capital: "Mogadishu" },
  SS: { name: "South Sudan", flag: "🇸🇸", capital: "Juba" },
  SD: { name: "Sudan", flag: "🇸🇩", capital: "Khartoum" },
  TZ: { name: "Tanzania", flag: "🇹🇿", capital: "Dodoma" },
  TG: { name: "Togo", flag: "🇹🇬", capital: "Lomé" },
  TN: { name: "Tunisia", flag: "🇹🇳", capital: "Tunis" },
  UG: { name: "Uganda", flag: "🇺🇬", capital: "Kampala" },
  ZM: { name: "Zambia", flag: "🇿🇲", capital: "Lusaka" },
  ZW: { name: "Zimbabwe", flag: "🇿🇼", capital: "Harare" },
    AG:{name:"Antigua and Barbuda",flag:"🇦🇬",capital:"Saint John's"},
  BS:{name:"Bahamas",flag:"🇧🇸",capital:"Nassau"},
  BB:{name:"Barbados",flag:"🇧🇧",capital:"Bridgetown"},
  BZ:{name:"Belize",flag:"🇧🇿",capital:"Belmopan"},
  BO:{name:"Bolivia",flag:"🇧🇴",capital:"Sucre"},
  CL:{name:"Chile",flag:"🇨🇱",capital:"Santiago"},
  CO:{name:"Colombia",flag:"🇨🇴",capital:"Bogotá"},
  CR:{name:"Costa Rica",flag:"🇨🇷",capital:"San José"},
  CU:{name:"Cuba",flag:"🇨🇺",capital:"Havana"},
  DM:{name:"Dominica",flag:"🇩🇲",capital:"Roseau"},
  DO:{name:"Dominican Republic",flag:"🇩🇴",capital:"Santo Domingo"},
  EC:{name:"Ecuador",flag:"🇪🇨",capital:"Quito"},
  SV:{name:"El Salvador",flag:"🇸🇻",capital:"San Salvador"},
  FJ:{name:"Fiji",flag:"🇫🇯",capital:"Suva"},
  GD:{name:"Grenada",flag:"🇬🇩",capital:"Saint George's"},
  GT:{name:"Guatemala",flag:"🇬🇹",capital:"Guatemala City"},
  GY:{name:"Guyana",flag:"🇬🇾",capital:"Georgetown"},
  HT:{name:"Haiti",flag:"🇭🇹",capital:"Port-au-Prince"},
  HN:{name:"Honduras",flag:"🇭🇳",capital:"Tegucigalpa"},
  JM:{name:"Jamaica",flag:"🇯🇲",capital:"Kingston"},
  KI:{name:"Kiribati",flag:"🇰🇮",capital:"South Tarawa"},
  MH:{name:"Marshall Islands",flag:"🇲🇭",capital:"Majuro"},
  FM:{name:"Micronesia",flag:"🇫🇲",capital:"Palikir"},
  NR:{name:"Nauru",flag:"🇳🇷",capital:"Yaren"},
  NI:{name:"Nicaragua",flag:"🇳🇮",capital:"Managua"},
  PW:{name:"Palau",flag:"🇵🇼",capital:"Ngerulmud"},
  PA:{name:"Panama",flag:"🇵🇦",capital:"Panama City"},
  PG:{name:"Papua New Guinea",flag:"🇵🇬",capital:"Port Moresby"},
  PY:{name:"Paraguay",flag:"🇵🇾",capital:"Asunción"},
  PE:{name:"Peru",flag:"🇵🇪",capital:"Lima"},
  KN:{name:"Saint Kitts and Nevis",flag:"🇰🇳",capital:"Basseterre"},
  LC:{name:"Saint Lucia",flag:"🇱🇨",capital:"Castries"},
  VC:{name:"Saint Vincent and the Grenadines",flag:"🇻🇨",capital:"Kingstown"},
  WS:{name:"Samoa",flag:"🇼🇸",capital:"Apia"},
  SB:{name:"Solomon Islands",flag:"🇸🇧",capital:"Honiara"},
  SR:{name:"Suriname",flag:"🇸🇷",capital:"Paramaribo"},
  TO:{name:"Tonga",flag:"🇹🇴",capital:"Nuku'alofa"},
  TT:{name:"Trinidad and Tobago",flag:"🇹🇹",capital:"Port of Spain"},
  TV:{name:"Tuvalu",flag:"🇹🇻",capital:"Funafuti"},
  UY:{name:"Uruguay",flag:"🇺🇾",capital:"Montevideo"},
  VU:{name:"Vanuatu",flag:"🇻🇺",capital:"Port Vila"},
  VE:{name:"Venezuela",flag:"🇻🇪",capital:"Caracas"},



};

export default countryData;